baseURL: https://electrodynamics.info
languageCode: ru
title: "Электродинамика: взгляд физика"
googleAnalytics: G-YBMK7NDJ5K
author: К. Б. Канн

markup:
  goldmark:
    renderer:
      # Enable inline HTML
      unsafe: true

disableKinds:
  - taxonomy
  - term

params:
  description: "Виртуальный мемориал доктора технических наук, профессора Константина Борисовича Канна (23.04.1936 — 28.12.2020). Изложение его видения современного состояния электродинамики, а также несостыковок и проблем, требующих дальнейших исследований и объяснений."
  keywords:
    - вихревое поле
    - гармонические индукционные процессы
    - гармонический индукционный электрогенератор
    - диск Фарадея
    - закон Ома
    - законы электромагнитной индукции
    - И.Е.Тамм
    - индукция
    - Ленц
    - магнетизм
    - магнитное поле
    - магнитный поток
    - Максвелл
    - парадокс Геринга
    - парадоксы физики
    - парадоксы электромагнитной индукции
    - сила Лоренца
    - современное состояние физики
    - стационарное поле
    - структура магнитного поля
    - Фарадей
    - физика
    - ЭДС
    - электрический заряд
    - электрический ток
    - электрическое поле
    - электродинамика
    - электромагнетизм
    - электромагнитная индукция
    - электромагнитные волны
    - электроэнергия
